name: Integración Continua

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: make -C hito3/api install

      - name: Set PYTHONPATH and Run tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/src"
          pytest --maxfail=1 --disable-warnings -v
        working-directory: hito3/api
