name: Integración Continua

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: make -C api install

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/moviebuster-api:latest ./api
          docker push ghcr.io/${{ github.repository }}/moviebuster-api:latest

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests in moviebuster-tests container
        run: docker-compose run --rm moviebuster-tests

      - name: Set PYTHONPATH and Run tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/src"
          pytest --maxfail=1 --disable-warnings -v
        working-directory: api